In [10]:
import tensorflow as tf

# 주어진 배열을 이용하여 (2,2,2,2) 차원의 텐서를 만듭니다.
data = [[[[6, 7],
          [6, 7]],
         [[1, 2],
          [8, 7]]]]
          
        # [[[3, 3],
        #   [3, 3]],
        #  [[4, 4],
        #   [4, 4]]]]

# 위 데이터를 텐서플로우 상수로 변환합니다.
sentence = tf.constant(data, dtype=tf.int32)

# A의 형태를 확인하여 (2,2,2,2) 차원의 텐서가 맞는지 확인합니다.
# print(A.shape)

In [11]:
sentence

<tf.Tensor: shape=(1, 2, 2, 2), dtype=int32, numpy=
array([[[[6, 7],
         [6, 7]],

        [[1, 2],
         [8, 7]]]], dtype=int32)>

In [12]:
resulta = tf.einsum("ibnd,jbnd->ijbn", sentence, sentence)
resulta

<tf.Tensor: shape=(1, 1, 2, 2), dtype=int32, numpy=
array([[[[ 85,  85],
         [  5, 113]]]], dtype=int32)>

In [ ]:
print(sentence[0,1,1,:])
print(sentence[0,1,1,:])

In [ ]:

# 결과를 저장할 리스트를 초기화합니다.
result_list = []

# 직접 계산하는 방식
for i in range(sentence.shape[0]):
    for j in range(sentence.shape[0]):  # 범위를 20으로 변경합니다.
        for b in range(sentence.shape[1]):
            for n in range(sentence.shape[2]):
                # temp_sum을 계산합니다.
                temp_sum = tf.reduce_sum(sentence[i, b, n, :] * sentence[j, b, n, :], axis=-1)
                # 결과 리스트에 추가합니다.
                result_list.append(temp_sum.numpy())

# 리스트를 텐서로 변환합니다.
result_tensor = tf.convert_to_tensor(result_list, dtype=tf.int32)
result_tensor = tf.reshape(result_tensor, (2, 2, 2, 2))

# einsum을 사용하는 방식
einsum_result = tf.einsum("ibnd,jbnd->ijbn", sentence, sentence)

# 두 결과가 동일한지 검증합니다.
print(tf.reduce_all(result_tensor == einsum_result).numpy())
print('result_tensor',result_tensor)

BD

In [ ]:
import numpy as np
w = np.array([
    [[[1, 1, 1, 1], [1, 1, 1, 1]],[[15, 15, 15, 15], [15, 15, 15, 15]]],
    [[[2, 2, 2, 2], [2, 2, 2, 2]],[[25, 25, 25, 25], [25, 25, 25, 25]]],
    [[[3, 3, 3, 3], [3, 3, 3, 3]],[[35, 35, 35, 35], [35, 35, 35, 35]]]])
# w = np.array([
#     [[[1, 1, 1, 1], [1, 1, 1, 1]]],
#     [[[2, 2, 2, 2], [2, 2, 2, 2]]],
#     [[[3, 3, 3, 3], [3, 3, 3, 3]]]])
k = np.array([
    [[1, 1, 1, 1],[1, 1, 1, 1]],
    [[2, 2, 2, 2],[2, 2, 2, 2]],
    [[3, 3, 3, 3],[3, 3, 3, 3]]
])

In [ ]:
# Implement the modified for loop to mimic the corrected einsum operation "ibnd,jnd->ijbn"
# Note: The output shape should be (3, 3, 1, 2) as per the einsum operation
output_modified = np.zeros((3, 3, 1, 2))

for i in range(w.shape[0]):
    for j in range(k.shape[0]):
        for b in range(w.shape[1]):  # Only one value for the third dimension
            for n in range(w.shape[2]):  # Only two values for the fourth dimension
                sum_value = 0
                for d in range(w.shape[3]):  # Sum over the last dimension of k and the third dimension of w
                    sum_value += w[i, 0, b, d] * k[j, b, d]
                output_modified[i, j, b, n] = sum_value

output_modified.shape, output_modified

In [ ]:
BD = tf.einsum("ibnd,jnd->ijbn", w, k)  # qlen x klen x bsz x n_head
BD

In [13]:
import tensorflow as tf

# Define the _rel_shift function
def _rel_shift(x):
    x_size = x.shape.as_list()

    x = tf.pad(x, [[0, 0], [1, 0], [0, 0], [0, 0]])
    x = tf.reshape(x, [x_size[1] + 1, x_size[0], x_size[2], x_size[3]])
    x = tf.slice(x, [1, 0, 0, 0], [-1, -1, -1, -1])
    x = tf.reshape(x, x_size)

    return x

# Create a sample tensor x with shape (3, 8, 1, 2)
x = tf.constant([[[[1, 2]], [[3, 4]], [[5, 6]], [[7, 8]], [[9, 10]], [[11, 12]], [[13, 14]], [[15, 16]]],
                 [[[17, 18]], [[19, 20]], [[21, 22]], [[23, 24]], [[25, 26]], [[27, 28]], [[29, 30]], [[31, 32]]],
                 [[[33, 34]], [[35, 36]], [[37, 38]], [[39, 40]], [[41, 42]], [[43, 44]], [[45, 46]], [[47, 48]]]])

# Apply the _rel_shift function to x
result = _rel_shift(x)

# Print the original and result tensors
print("Original x:")
print(x.numpy())
print("\nResult after applying _rel_shift:")
print(result.numpy())

Original x:
[[[[ 1  2]]

  [[ 3  4]]

  [[ 5  6]]

  [[ 7  8]]

  [[ 9 10]]

  [[11 12]]

  [[13 14]]

  [[15 16]]]


 [[[17 18]]

  [[19 20]]

  [[21 22]]

  [[23 24]]

  [[25 26]]

  [[27 28]]

  [[29 30]]

  [[31 32]]]


 [[[33 34]]

  [[35 36]]

  [[37 38]]

  [[39 40]]

  [[41 42]]

  [[43 44]]

  [[45 46]]

  [[47 48]]]]

Result after applying _rel_shift:
[[[[ 5  6]]

  [[ 7  8]]

  [[ 9 10]]

  [[11 12]]

  [[13 14]]

  [[15 16]]

  [[ 0  0]]

  [[17 18]]]


 [[[19 20]]

  [[21 22]]

  [[23 24]]

  [[25 26]]

  [[27 28]]

  [[29 30]]

  [[31 32]]

  [[ 0  0]]]


 [[[33 34]]

  [[35 36]]

  [[37 38]]

  [[39 40]]

  [[41 42]]

  [[43 44]]

  [[45 46]]

  [[47 48]]]]
